### ISSUE TITLE
Error with download_pubmlst_latest.py

### ISSUE THREAD

**Issue by domenico-simone** [lmc297/BTyper3#2]
```
$ python download_pubmlst_latest.py

Downloading most recent PubMLST datbase at 2021-04-12 14:38
Traceback (most recent call last):
  File "download_pubmlst_latest.py", line 74, in <module>
    main()
  File "download_pubmlst_latest.py", line 67, in main
    download_pubmlst(btyper3_path)
  File "download_pubmlst_latest.py", line 28, in download_pubmlst
    tree=ET.parse(xml)
  File "/home/domeni/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/domeni/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

I'm not very familiar with the `requests` and the `xml` modules this error seems to be related with. Any clue?

Thank you

Domenico

**Comment by lmc297** [comment]
Hello Domenico,

Thanks so much for letting me know! It looks like I had made an indentation-related typo that would sometimes make `xml` throw an error. 

Everything should be fixed in the latest BTyper3 version (`3.1.2`; alternatively, if you don't feel like re-downloading everything again, you can just <a href="https://github.com/lmc297/BTyper3/blob/master/download_pubmlst_latest.py">download the latest download_pubmlst_latest.py script</a> because that's the only place I made changes).

If you run into any problems, or if that didn't fix it, just let me know!

Laura

**Comment by domenico-simone** [comment]
Hi Laura,

thanks for your quick reply and fix! If I understand correctly, a `git pull` should do the job, right?

Domenico

**Comment by domenico-simone** [comment]
Ahah nevermind, I've pulled the changes. Sorry for the laziness :)
